"""
Challenge derivation and verification for anti-prerecording liveness system.

The challenge is derived deterministically from a seed so the mobile app 
and backend compute the same challenge independently.

HMAC signatures ensure challenge responses cannot be tampered with.
"""
import hashlib
import hmac
import time
from typing import Tuple, Optional
from enum import Enum


class ChallengeType(str, Enum):
    SMILE = "smile"                  # Smile at the camera
    BLINK = "blink"                  # Blink eyes
    TURN_HEAD_LEFT = "turn_head_left"     # Turn head left
    TURN_HEAD_RIGHT = "turn_head_right"   # Turn head right


# All possible challenges with their parameter ranges
CHALLENGE_DEFINITIONS = {
    ChallengeType.SMILE: {"param_range": (1, 1)},            # No param
    ChallengeType.BLINK: {"param_range": (1, 3)},            # 1-3 blinks
    ChallengeType.TURN_HEAD_LEFT: {"param_range": (1, 1)},   # No param
    ChallengeType.TURN_HEAD_RIGHT: {"param_range": (1, 1)},  # No param
}


def derive_challenge_from_seed(seed: str) -> Tuple[ChallengeType, int]:
    """
    Derive a deterministic challenge from a seed.
    Same seed always produces same challenge (for verification).
    
    Args:
        seed: Hex string from QR token (e.g., "a1b2c3d4")
    
    Returns:
        Tuple of (ChallengeType, parameter)
    """
    # Hash the seed to get a deterministic but unpredictable value
    hash_bytes = hashlib.sha256(seed.encode()).digest()
    
    # Use first 4 bytes to select challenge type
    challenge_types = list(ChallengeType)
    type_index = int.from_bytes(hash_bytes[0:2], 'big') % len(challenge_types)
    challenge_type = challenge_types[type_index]
    
    # Use next 2 bytes to select parameter within range
    param_range = CHALLENGE_DEFINITIONS[challenge_type]["param_range"]
    param_min, param_max = param_range
    if param_min == param_max:
        param = param_min
    else:
        param_span = param_max - param_min + 1
        param = param_min + (int.from_bytes(hash_bytes[2:4], 'big') % param_span)
    
    return challenge_type, param


def get_challenge_instruction(challenge_type: ChallengeType, param: int) -> str:
    """
    Get human-readable instruction for a challenge.
    """
    instructions = {
        ChallengeType.SMILE: "Please SMILE at the camera",
        ChallengeType.BLINK: f"Blink your eyes {param} time{'s' if param > 1 else ''}",
        ChallengeType.TURN_HEAD_LEFT: "Turn your head slightly LEFT",
        ChallengeType.TURN_HEAD_RIGHT: "Turn your head slightly RIGHT",
    }
    return instructions.get(challenge_type, "Complete the liveness check")


def verify_challenge_response(
    seed: str,
    submitted_type: str,
    submitted_param: int,
    response_time_ms: int,
    challenge_completed: bool
) -> Tuple[bool, str]:
    """
    Verify that the submitted challenge response matches expected.
    
    Args:
        seed: Challenge seed from QR token
        submitted_type: Challenge type the user claims to have completed
        submitted_param: Challenge parameter the user submitted
        response_time_ms: Time taken to complete challenge
        challenge_completed: Whether the user reports completing it
    
    Returns:
        Tuple of (passed, reason)
    """
    if not challenge_completed:
        return False, "Challenge not completed"
    
    # Derive expected challenge
    expected_type, expected_param = derive_challenge_from_seed(seed)
    
    # Verify challenge type matches
    if submitted_type != expected_type.value:
        return False, f"Challenge type mismatch: expected {expected_type.value}, got {submitted_type}"
    
    # Verify parameter matches (for blink count challenges)
    if expected_type == ChallengeType.BLINK:
        if submitted_param != expected_param:
            return False, f"Challenge parameter mismatch: expected {expected_param}, got {submitted_param}"
    
    # Anti-automation: check response time
    # Real humans take 1-10 seconds, automation is instant
    if response_time_ms < 800:
        return False, f"Response too fast ({response_time_ms}ms) - possible automation"
    
    if response_time_ms > 20000:
        return False, f"Response too slow ({response_time_ms}ms) - timeout"
    
    return True, "Challenge verified successfully"


def _get_hmac_secret() -> bytes:
    """Get the HMAC secret from settings."""
    from backend.core.config import get_settings
    settings = get_settings()
    # Use QR_SECRET_KEY as the HMAC key (already configured)
    return settings.QR_SECRET_KEY.encode()


def generate_challenge_signature(
    seed: str,
    challenge_type: str,
    challenge_param: int,
    timestamp_ms: Optional[int] = None
) -> str:
    """
    Generate HMAC signature for a challenge response.
    
    This signature is generated by the mobile app and verified by the backend
    to ensure the challenge data hasn't been tampered with.
    
    Args:
        seed: Challenge seed from QR token
        challenge_type: The challenge type being completed
        challenge_param: The challenge parameter
        timestamp_ms: Optional timestamp (uses current time if not provided)
    
    Returns:
        Hex-encoded HMAC-SHA256 signature
    """
    if timestamp_ms is None:
        timestamp_ms = int(time.time() * 1000)
    
    # Create deterministic message to sign
    message = f"{seed}|{challenge_type}|{challenge_param}|{timestamp_ms}"
    
    signature = hmac.new(
        _get_hmac_secret(),
        message.encode(),
        hashlib.sha256
    ).hexdigest()
    
    return signature


def verify_challenge_signature(
    seed: str,
    challenge_type: str,
    challenge_param: int,
    timestamp_ms: int,
    signature: str,
    max_age_ms: int = 30000  # 30 seconds max age
) -> Tuple[bool, str]:
    """
    Verify HMAC signature of a challenge response.
    
    Args:
        seed: Challenge seed from QR token
        challenge_type: The challenge type submitted
        challenge_param: The challenge parameter submitted
        timestamp_ms: Timestamp when challenge was completed
        signature: The HMAC signature to verify
        max_age_ms: Maximum allowed age of the signature
    
    Returns:
        Tuple of (valid, reason)
    """
    # Check timestamp freshness to prevent replay attacks
    current_time_ms = int(time.time() * 1000)
    age_ms = current_time_ms - timestamp_ms
    
    if age_ms > max_age_ms:
        return False, f"Challenge signature expired ({age_ms}ms old, max {max_age_ms}ms)"
    
    if age_ms < -5000:  # Allow 5s clock skew into future
        return False, "Challenge signature from the future - clock skew detected"
    
    # Regenerate expected signature
    expected_signature = generate_challenge_signature(
        seed, challenge_type, challenge_param, timestamp_ms
    )
    
    # Constant-time comparison to prevent timing attacks
    if not hmac.compare_digest(signature, expected_signature):
        return False, "Invalid challenge signature - possible tampering"
    
    return True, "Signature verified"


def verify_challenge_response_with_hmac(
    seed: str,
    submitted_type: str,
    submitted_param: int,
    response_time_ms: int,
    challenge_completed: bool,
    signature: Optional[str] = None,
    signature_timestamp_ms: Optional[int] = None
) -> Tuple[bool, str]:
    """
    Enhanced challenge verification with optional HMAC signature validation.
    
    Falls back to basic verification if signature is not provided (backward compatibility).
    
    Args:
        seed: Challenge seed from QR token
        submitted_type: Challenge type the user claims to have completed
        submitted_param: Challenge parameter the user submitted
        response_time_ms: Time taken to complete challenge
        challenge_completed: Whether the user reports completing it
        signature: Optional HMAC signature for tamper protection
        signature_timestamp_ms: Timestamp used in signature generation
    
    Returns:
        Tuple of (passed, reason)
    """
    # First, do basic verification
    passed, reason = verify_challenge_response(
        seed, submitted_type, submitted_param, response_time_ms, challenge_completed
    )
    
    if not passed:
        return passed, reason
    
    # If signature provided, verify it
    if signature and signature_timestamp_ms:
        sig_valid, sig_reason = verify_challenge_signature(
            seed, submitted_type, submitted_param, signature_timestamp_ms, signature
        )
        if not sig_valid:
            return False, sig_reason
    
    return True, "Challenge verified with signature"

